### ISSUE TITLE
Add username option to login screen

### ISSUE THREAD

**Issue by appsforartists** [hhd-dev/hhd-ui#1]
Terminals aren't touchscreen friendly.  (I just had GNOME Mobile crash twice on me when I tried to finger-copy the token, though that's more of a GNOME Mobile thing...)

Investigate if it's possible to `<a href = "file:///home/YOUR_NAME_HERE/.config/hhd/token">`.  If so, offer that link as an alternative to `cat`.

**Comment by antheas** [comment]
That's a great idea.

I made the token easy enough to copy by hand but we can try to do something like that

The token is also important for consent but that's a different discussion

As for gnome mobile, haven't heard of it. Would recommend normal gnome instead. It's so mobile that you need a bunch of extensions for it to work like a desktop

**Comment by antheas** [comment]
Not possible unfortunately due to security reasons.
