### ISSUE TITLE
Controller navigation in sliders

### ISSUE THREAD

**Issue by 522122** [hhd-dev/hhd-ui#11]
Confirmation with `A` is not working, it reverts to last saved value.

For example charge limit slider.

Starting value 80%

Move left thumbstick to the right calls `updateSettingValue` with values `path: 'tdp.asus.charge_limit', value: 'p85`

Confirm with `A` -> `updateSettingValue` is called with last saved value `p80`

**Comment by 522122** [comment]
It has something to do with `sel_choice`. 
Value is already updated on "server" but sel_choice remains. By pressing 'A' it will revert

**Comment by antheas** [comment]
I verified that pressing A breaks the slider. I never pressed A anymore and only used B so I never noticed.

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd-ui/releases/tag/v3.2.1
