### ISSUE TITLE
Handle Errors Gracefully

### ISSUE THREAD

**Issue by antheas** [hhd-dev/hhd-ui#4]
Right now, if there is an error in the UI, it is not caught and the browser displays an error.

There should be a topmost container handling the errors, or preferably, a per-setting container that only disables a particular broken setting (the per-setting container can wrap the render child function, it does not have to be per setting type).

**Comment by aarron-lee** [comment]
added error containers to each hhd component, so it containers the error per-setting

![image](https://github.com/hhd-dev/hhd-ui/assets/9145965/2c1c1b32-00b7-4e7d-82dd-cf2aefa5eecc)
