### ISSUE TITLE
Opening the "Charge Limit %" in full screen overlay crashes hhd-ui in Rog Ally

### ISSUE THREAD

**Issue by wolfyreload** [hhd-dev/hhd-ui#9]
Hardware 
```
Device: Rog Ally
```

Software
```
OS: bazzite-deck 40.20240630.0
Handheld Daemon Version: 3.0.0 
Handheld Daemon UI Version: 3.0.0 
Adjustor (TDP) version: 3.0.0. 
```

Steps to reproduce:

* Open hhd-ui by pressing QAM 3 times (in game mode)
* Try and open Charge limit % dropdown with ROG ally controller or any other external USB controller
* HHD ui crashes and you can no longer select anything

Work around is to open a TTY session with CTRL+ALT+F2 and kill hhd-ui in btop and switch back to TTY 1 with CTRL+ALT+F1.

Note that the dropdown works correctly when accessing it via a mouse, so it seems to be specific to controllers.

Also the hhd sidebar plugin that is embedded in decky seems to work correctly with no crash. Issue appears to only be with the full screen version of hhd-ui

See attached [hhd.log](https://github.com/user-attachments/files/16048798/hhd.log). Please let me know if you require any additional information

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd-ui/releases/tag/v3.0.1
https://github.com/hhd-dev/hhd-ui/commit/197b39a7eca37e5b6fe2279c273960ae88b99f11
